### ISSUE TITLE
XMLLexicon entry changed when sentence is realised.

### ISSUE THREAD

**Issue by cchowell** [simplenlg/simplenlg#16]
Debugging to find the cause of a word mysteriously becoming plural determined that the cause was a change to the content of the XMLLexicon as a result of realising a sentence with the word in plural form. 

This code, written as an XMLLexicon unit test demonstrates the problem.

	@Test
	public void testLexiconImmutability() {
		NLGFactory factory = new NLGFactory(lexicon);
		Realiser realiser = new Realiser(lexicon);
		
		// "wall" is singular.
		NPPhraseSpec wall = factory.createNounPhrase("the", "wall");
		assertEquals(NumberAgreement.SINGULAR, wall.getFeature(Feature.NUMBER));	
		
		// Realise a sentence with plural form of "wall"
		wall.setPlural(true);		
		SPhraseSpec sentence = factory.createClause("motion", "observe");
		sentence.setFeature(Feature.TENSE, Tense.PAST);	
		PPPhraseSpec pp = factory.createPrepositionPhrase("in", wall);
		sentence.addPostModifier(pp);
		String text = realiser.realiseSentence(sentence);
		
		// This assertion fails. Lexicon entry has become plural!
		wall = factory.createNounPhrase("the", "wall");
		assertEquals(NumberAgreement.SINGULAR, wall.getFeature(Feature.NUMBER));	
	}

**Comment by Saad-Mahamood** [comment]
Chris, I'll get back to you with an answer on Friday.

**Comment by Saad-Mahamood** [comment]
I've had a look at and might need more time to fix this. The underlying issue is that when you call the realiser to realise a syntactic sentence structure it then propagates features such as "number" in the Syntax processor, which is needed for things like subject-verb agreement. I suspect what is happening is that the syntax processor is also propagating these features into the WordElements themselves. Since WordElements are NLGElements (which is an abstract class, that contains the features Map) this means that the features are now in the "wall" lexical entry as well. For now, the only work around I can offer is to re-initalise the Lexicon, NLGFactory, and Realiser after calling realiser.realiseSentence until I have time to investigate more fully.

**Comment by Saad-Mahamood** [comment]
Lines 119-120 is where in NounPhraseHelper is where the Number feature is being propagated from the phrase to the WordElement. 

To fix this properly I will need to break the link between Lexical entries and WordElements. This means create a new class called "LexicalEntry" that does not extend NLGElement and is converted to a WordElement in the Lexicon class.

**Comment by cchowell** [comment]
That seems like a good approach that will make the XLMLexicon more lightwieght in memory. I have a workaround for now, and will be switching to NIHDBLexicon soon, where this doesn't happen.

**Comment by Saad-Mahamood** [comment]
I have committed a fix for this issue, by making sure that the XML based Lexicon always returns a new WordElement object instead of passing the reference of the WordElement in the Lexicon HashMap. Thus, this should stop the unintended feature propagation. I've used your JUnit code above and have included it in the XMLLexiconTest class.

**Comment by Saad-Mahamood** [comment]
Going to close this issue as it should now be fixed. If there is a reoccurrence or another unintended problem please file another issue ticket.
