### ISSUE TITLE
Cannot work out the plural of "this"

### ISSUE THREAD

**Issue by fmestrone** [simplenlg/simplenlg#30]
HI all, I may be missing something but I'm trying an example that I thought would be really basic, and failing...

```
NPPhraseSpec obj = nlgFactory.createNounPhrase("monkey");
obj.setPlural(true);
obj.setDeterminer("a");
```

This correctly results in "some monkeys", so I logically expected the following

```
NPPhraseSpec obj = nlgFactory.createNounPhrase("monkey");
obj.setPlural(true);
obj.setDeterminer("this");
```

to result in "these monkeys", but it doesn't, it thinks it should be "this monkeys" instead.

So I tried treating "this" as a separate noun

```
NPPhraseSpec det = nlgFactory.createNounPhrase("this");
det.setPlural(true);
NPPhraseSpec obj = nlgFactory.createNounPhrase("monkey");
obj.setPlural(true);
obj.setDeterminer(det);
```

and that was even more intriguing "thises monkeys"!

Am I doing something wrong? Surely "this"/"that" should be known in the lexicon?

**Comment by rdeoliveira** [comment]
It looks like the change a => some happens at:

MorphologyRules.doDeterminerMorphology()

Which uses the realisation string of the determiner (an NLGElement) to decide which transformation to do. The only string the method changes is “a”, which can be transformed into “some” or “an”.

I suppose this also means that SimpleNLG doesn’t look at its lexicon to do determiner morphology.

It should be straightforward to modify the method above to do morphology for “this” (and possibly all other determiners).

— Rodrigo

On 5 May 2016, at 13:38, Federico Mestrone <notifications@github.com<mailto:notifications@github.com>> wrote:


NPPhraseSpec obj = nlgFactory.createNounPhrase("monkey");
obj.setPlural(true);
obj.setDeterminer("a");



The University of Aberdeen is a charity registered in Scotland, No SC013683.
Tha Oilthigh Obar Dheathain na charthannas clàraichte ann an Alba, Àir. SC013683.

**Comment by fmestrone** [comment]
Thank you! Actually, I looked at the lexicon and "this"/"that", "these"/"those" are all registered as separate entries, rather than having "these"/"those" as the plural of "this"/"that"...

**Comment by rdeoliveira** [comment]
Ah interesting. That’s one question answered. The other question is whether SimpleNLG uses the knowledge in the lexicon to do determiner morphology…

— Rodrigo

On 6 May 2016, at 10:43, Federico Mestrone <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you! Actually, I looked at the lexicon and "this"/"that", "these"/"those" are all registered as separate entries, rather than having "these"/"those" as the plural of "this"/"that"...

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/simplenlg/simplenlg/issues/30#issuecomment-217398899>



The University of Aberdeen is a charity registered in Scotland, No SC013683.
Tha Oilthigh Obar Dheathain na charthannas clàraichte ann an Alba, Àir. SC013683.

**Comment by Saad-Mahamood** [comment]
Apologies for answering this question late. As for Rodrigo's question SimpleNLG does not currently use lexicon when doing determiner morphology. However, I have changed this with my most recent commit and it will look at the lexicon for plural forms for a given determiner and use lexical entry if available. 

I have also amended the XML lexicon entries for determiners this and that and added plural entries for both and removed these and those determiner base form entries.

**Comment by rdeoliveira** [comment]
This is brilliant Saad!

Just a minor comment: won’t it be an issue to remove “these” and “those” from the XML lexicon? I’m thinking of the opposite direction: what if a user provides “these” in the sentence specification and needs its singular form “this” in the output?

— Rodrigo

On 8 May 2016, at 02:03, Saad Mahamood <notifications@github.com<mailto:notifications@github.com>> wrote:


Apologies for answering this question late. As for Rodrigo's question SimpleNLG does not currently use lexicon when doing determiner morphology. However, I have changed this with my most recent commit and it will look at the lexicon for plural forms for a given determiner and use lexical entry if available.

I have also amended the XML lexicon entries for determiners this and that and added plural entries for both and removed these and those determiner base form entries.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/simplenlg/simplenlg/issues/30#issuecomment-217681335>



The University of Aberdeen is a charity registered in Scotland, No SC013683.
Tha Oilthigh Obar Dheathain na charthannas clàraichte ann an Alba, Àir. SC013683.

**Comment by Saad-Mahamood** [comment]
Unfortunately after more testing I have had to rip out the use of the Lexicon for determiner morphology inflection. I have reverted back to use hardcoded rules for now. The main problem whilst I can get this to partial work for the XML based default lexicon the NIHDB lexicon also contains the same erroneous entries of not have plural forms for _this_ and _that_ base forms and needs correcting as well. For now I've gone for the simplest solution and I will take a look at this problem again later.
