### ISSUE TITLE
Can i use nlp4j with spanish?

### ISSUE THREAD

**Issue by elgamersitom** [simplenlg/simplenlg#32]
Hello,
I was thinking about using this library in a research project, the fact is that the project is oriented to work with spanish words. Is there any way to use the library with spanish?.

Tanks. 😄

**Comment by Saad-Mahamood** [comment]
Unfortunately, this surface realiser is English only. Whilst, other language versions have been created in the past including a French, German, and Brazilian-Portuguese, I'm not aware of a Spanish version. To create Spanish version of SimpleNLG would be a considerable undertaking due to the fact that you will need to acquire a Spanish Lexicon, understand Spanish language syntax reorder, feature unification, verb group formation rules, morphological rules, determiner agreement rules, word contract rules (if any), and have some understanding of Spanish Orthography rules.

**Comment by elgamersitom** [comment]
ok i understand, i will search for more info.

 thank you 👍
