### ISSUE TITLE
using the determiner 'both' instead of 'some'

### ISSUE THREAD

**Issue by AlJohri** [simplenlg/simplenlg#39]
Hi @Saad-Mahamood,

Currently when the determiner is "a" and plural, it will become "some". I'm running into a case where instead of "some" I need to say "both".

> Person A and Person B, _both_ clowns, are riding a bicycle.

src/main/java/simplenlg/morphology/english/MorphologyRules.java

```
if(determiner.getRealisation().equals("a")) { //$NON-NLS-1$
    if(determiner.isPlural()) {
        determiner.setRealisation("some");
    } else if(DeterminerAgrHelper.requiresAn(realisation)) {
        determiner.setRealisation("an");
    }
}
```
1. Can you think of a way of abstracting this other than hardcoding this on my side? It seems like SimpleNLG not only needs to know that it is plural but that it is plural with 2 items.
2. If I do hardcode this on my side anytime the determiner is plural with 2 items, are there situations where saying
   
   > A and B, some ....
   
   is preferred over
   
   > A and B, both ....
   
   ?

Thanks!

Related Issues:

https://github.com/simplenlg/simplenlg/pull/31
https://github.com/simplenlg/simplenlg/issues/30

**Comment by rdeoliveira** [comment]
@AlJohri, this is very interesting! I think your strategy of going from "a" to "both" is generally safe when when aggregating 2 elements, but **only when these are appositives**. This is because "both" seems to have an anaphoric element to it, so if I read "both" in a text, I'd expect to know from discourse (or context) which 2 entities the text is referring to, before I read "both". Note that without context (e.g. the beginning of the text), it may sound weird to default the plural of 2 elements to "both":

- "A clown[clown_A] is riding a bike." + "A clown[clown_B] is riding a bike." = "Two clowns are riding a bike." 

It would be weird to say "Both clowns are riding a bike" if it's the first time you talk about clowns in the text; but if "a clown" is appositive of something else (as it is in your example), then the context is there to allow "both" to be said. 

And what is your strategy to handle 3 or more elements? Transform "a" to "all", e.g. "Person A, Person B and Person C, _all_ clowns, are riding a bicycle"?

**Comment by Saad-Mahamood** [comment]
No response after @rdeoliveira answer. Closing this issue. Feel free to re-open if this is not sufficient.
