### ISSUE TITLE
Expected form of "be" is "is", but I get " 's "

### ISSUE THREAD

**Issue by godlark** [simplenlg/simplenlg#46]
Hi,

Here is my code in Scala:
```
val lexicon = new NIHDBLexicon("lexAccess2016.data")
val realiser = new Realiser()

val v = lexicon.getWord("be", POS.VERB), LexicalCategory.VERB)
v.setFeature(simplenlg.features.Feature.PERSON, simplenlg.features.Person.THIRD)
realiser.realise(v).getRealisation
```

I do not see any feature to avoid the contracted form. I always get " 's " instead of "is"

**Comment by Saad-Mahamood** [comment]
The problem here is that lexicon.getWord returns a WordElement, which is not being wrapped into Phrase that indicates the type of phrase it is e.g. Noun Phrase, Verb Phrase, etc. In your case you need to place val v into a Verb Phrase PhraseElement which then enable the syntax processor to perform verb group formation.
