### ISSUE TITLE
When there are multiple subjects set in setSubject(), setVerb() does not recognize the number of subjects. Singular verb was used instead of Plural.

### ISSUE THREAD

**Issue by JeevaTM** [simplenlg/simplenlg#63]
OS: Windows 10 Pro
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

The name were in list. I concatenated that in a format like, "Jeeva, Bharathi, Anand, and Jackulin"
I set the subject from this line
`object.setSubject("Jeeva, Bharathi, Anand, and Jackulin");`

I gave an conditon, if there are more than 1 element in list `setVerb("are")`, else `setVerb("is")`.

But it ignored the condition, and set the verb as "is".

**Comment by rdeoliveira** [comment]
Instead of changing the verb, **make the clause plural**, when more than 1 element:

```
Lexicon lexicon = Lexicon.getDefaultLexicon();
NLGFactory phraseFactory = new NLGFactory(lexicon);
Realiser realiser = new Realiser(lexicon);
		
SPhraseSpec c = phraseFactory.createClause();
c.setVerb("is");
c.setComplement("here");

c.setSubject("Jeeva");
System.out.println(realiser.realiseSentence(c)); // Jeeva is here.
		
c.setSubject("Jeeva, Bharathi, Anand, and Jackulin");
c.setFeature(Feature.NUMBER, NumberAgreement.PLURAL);
System.out.println(realiser.realiseSentence(c)); // Jeeva, Bharathi, Anand, and Jackulin are here.
```

SimpleNLG will automatically transform "are" to "is", because it converts words to their base forms (are -> be), then it applies morphological features to base words. Because you haven't specifically set number to plural, the default singular is used (be -> is). So, if you set the verb to any form of "be" (are, is, am, was, were or be), and nothing else, then you'll get "is" in the output; if you set number to plural, then you get "are".

**Comment by JeevaTM** [comment]
Thank you for the very detailed explanation.
