### ISSUE TITLE
Can't apply method addComplement on an NLGElement

### ISSUE THREAD

**Issue by Vonisoa** [simplenlg/simplenlg#70]
Hi, I see from [this documentation](https://github.com/simplenlg/simplenlg/blob/master/docs/SimpleNLGv4%20Architecture.pdf) that we can apply the method addComplement on an NLGElement, but when I try this code:
```
Lexicon lexicon= new XMLLexicon();
NLGFactory factory = new NLGFactory(lexicon);
NLGElement s1 = factory.createSentence("my dog is happy");
s1.addComplement("with me");
```
I got the following error:

> The method addComplement() is undefined for the type NLGElement

So can anyone explain and help if there is an other alternative to add complement on an NLGElement

**Comment by rdeoliveira** [comment]
So, the doc is wrong because only `PhraseElement`s implement `addComplement`, not `NLGElement`. The doc is over 10 years old now =)

Not sure what you're trying to achieve, but I can see 2 options:

1. If your text is always canned, perhaps you can just concatenate strings beforehand:

```
String sentence = "my dog is happy";
String complement = "with me";
NLGElement s1 = factory.createSentence(sentence + " " + complement);
System.out.println(realiser.realiseSentence(s1)); // My dog is happy with me.
```

2. But if you do need the linguistic notion of a complement, then you can use an `SPhraseSpec`, a subtype of `PhraseElement`, create a clause with specific subject, verb and object, then add a complement to it:
```
SPhraseSpec s1 = nlgFactory.createClause("my dog", "is", "happy");
s1.addComplement("with me");
System.out.print(realiser.realiseSentence(s1)); // My dog is happy with me.
```
